.TH GNODUINO 1 "02 Jul 2011"
.SH NAME
\fBgnoduino\fP \- AVR development board IDE for the GNOME desktop

.SH SYNOPSIS
.B gnoduino
[\fIOPTION\fR]... [\fIFILE\fR]...
.SH DESCRIPTION
.B gnoduino
is a AVR development board IDE for the GNOME desktop environment.

While aiming at simplicity and ease of use,
.B gnoduino
is a powerful integrated development environment.
It can be used to create and edit all kinds of microcontroller projects.
.LP
.SH OPTIONS

.TP
\fB\-\-help\fR
Prints the command line options.
.TP
\fB\-\-version\fR
Output version information and exit

.SH BUGS
If you find a bug, please report it at http://bugzilla.gnome.eu.org/enter_bug.cgi?product=gnoduino.
.SH AUTHORS
Lucian Langa (lucilanga@gnome.org)

